# Generated by Django 4.2.4 on 2023-08-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passApp', '0002_rename_passwordbucket_passworditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passworditem',
            name='username',
        ),
    ]
