# Generated by Django 4.2.4 on 2023-08-18 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passApp', '0003_remove_passworditem_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], max_length=10)),
                ('password_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passApp.passworditem')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
